"""Fixing fields

Revision ID: 4ffa5307da69
Revises: b72ecd46bfd0
Create Date: 2024-12-01 11:41:05.694761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ffa5307da69'
down_revision: Union[str, None] = 'b72ecd46bfd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
